# clinical-safety.yml
name: Clinical Safety Checks

on:
  push:
    branches: [main]
    paths:
      - 'ai/ml-models/**'
      - 'medical-content/decision-support-rules/**'

jobs:
  safety-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Clinical Validation Tests
        uses: docker://healthcarevalidation/clinical-validator:latest
        with:
          args: --test-dir ./medical-content/decision-support-rules --output report.html
          
      - name: Upload Safety Report
        uses: actions/upload-artifact@v2
        with:
          name: clinical-safety-report
          path: report.html
          
      - name: Require Manual Approval
        if: ${{ failure() }}
        run: |
          echo "Clinical safety checks failed. Manual review required." >&2
          exit 1