# fhir-validation.yml
name: FHIR Resource Validation

on:
  pull_request:
    paths:
      - 'server/api/v2/fhir/**'
      - 'client/src/lib/fhir/**'

jobs:
  validate-fhir:
    runs-on: ubuntu-latest
    container: ghcr.io/linuxforhealth/fhir-validator:latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Validate FHIR Resources
        run: |
          for file in $(find . -name '*.json'); do
            if jq -e '.resourceType' "$file" >/dev/null; then
              echo "Validating $file"
              fhir validate --file "$file" --profile hl7.fhir.r4.core#4.0.1
            fi
          done